name: Deploy book
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push to a branch
      pull-requests: write  # To create a PR from that branch
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history to ensure full context for deployment

    - name: Install latest mdbook
      run: |
        # Fetch the latest release tag from the mdbook repository
        tag=$(curl -s 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
        url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
        
        # Create a directory for mdbook and install it
        mkdir -p mdbook
        curl -sSL $url | tar -xz --directory=./mdbook
        echo $(pwd)/mdbook/bin >> $GITHUB_PATH  # Add the mdbook binary to the path

    - name: Generate CLI docs and inject them into the book
      run: |
        # Generate the markdown help for the CLI and inject it into the book
        cargo run --package powdr_cli -- --markdown-help > book/src/cli/README.md

    - name: Build and deploy the book to GitHub Pages
      run: |
        # Build the book
        cd book
        mdbook build

        # Set up git for deploying to gh-pages
        git worktree add gh-pages
        git config user.name "Deploy from CI"
        git config user.email "deploy@example.com"  # Replace with your email

        # Prepare gh-pages
        cd gh-pages
        git update-ref -d refs/heads/gh-pages  # Delete the previous gh-pages reference
        rm -rf *  # Clean up old files

        # Move the generated book content to the gh-pages branch
        mv ../book/* . 
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        
        # Push to gh-pages branch with force
        git push --force --set-upstream origin gh-pages
